[project]
authors = [
  {name = "SunDaha", email = "sunkangcheng0@gmail.com"},
]
dependencies = [
  "anthropic>=1.2.0",
  "dotenv>=0.9.9",
  "openai>=3.6.0",
  "pyyaml>=6.0.3",
  "tiktoken>=0.14.0",
]
description = "DFAgent Framework"
name = "dfagent"
readme = "README.md"
requires-python = ">=3.12"
version = "0.1.0"

[project.scripts]
dfagent = "dfagent:main"

[build-system]
build-backend = "uv_build"
requires = ["uv_build>=0.12.3,<0.13.0"]
